### ISSUE TITLE
Charta - Tereza 

### ISSUE THREAD

**Issue by Hajneken** [Hajneken/3MA114-Projekt#11]
Belbin = role
SWOT
Účet na Toggle
Účet na GitHubu
napsat Hynkovi aby vás přidal do projektu
min. 5 vět o sobě

**Comment by JednorozecTerezka** [comment]
[Charta.docx](https://github.com/Hajneken/3MA114-Projekt/files/1364519/Charta.docx)

Belbin - stmelovač
