### ISSUE TITLE
Formát dokumentu s poznámkami

### ISSUE THREAD

**Issue by Hajneken** [Hajneken/3MA114-Projekt#16]
zformátuj to co ti pošlu prosím, pro výsledné odevzdání

**Comment by antydex** [comment]
[Schůze_2 - semifinal (chybí screen hovoru).docx](https://github.com/Hajneken/3MA114-Projekt/files/1404519/Schuze_2.-.semifinal.chybi.screen.hovoru.docx)

**Comment by Hajneken** [comment]
good job
