### ISSUE TITLE
Zápis ze schůzky č. 4

### ISSUE THREAD

**Issue by Hajneken** [Hajneken/3MA114-Projekt#19]
Prosím o sepsání zápisu, ze schůzky.

Zahrň např.:
- Den a čas schůzky
- Zúčastnění
- Co jsme řešili
- Na čem jsme se shodli
- Jaké jsou výsledky

**Comment by fedv00** [comment]
[sh.4.docx](https://github.com/Hajneken/3MA114-Projekt/files/1443691/sh.4.docx)
