### ISSUE TITLE
Charta - Jakub

### ISSUE THREAD

**Issue by Hajneken** [Hajneken/3MA114-Projekt#2]
- Belbin = role 
- SWOT
- Účet na Toggle 
- Účet na GitHubu 
- napsat Hynkovi aby vás přidal do projektu 
- min. 5 vět o sobě

**Comment by antydex** [comment]
[Charta - Kuba.docx](https://github.com/Hajneken/3MA114-Projekt/files/1384780/Charta.-.Kuba.docx)

**Comment by Hajneken** [comment]
good job
