### ISSUE TITLE
Charta - Vladimir 

### ISSUE THREAD

**Issue by Hajneken** [Hajneken/3MA114-Projekt#3]
- Belbin = role 
- SWOT
- Účet na Toggle 
- Účet na GitHubu 
- napsat Hynkovi aby vás přidal do projektu 
- min. 5 vět o sobě

**Comment by fedv00** [comment]
[Vl_Fed.docx](https://github.com/Hajneken/3MA114-Projekt/files/1364559/Vl_Fed.docx)

**Comment by Hajneken** [comment]
Good Job, díky :)
