### ISSUE TITLE
Zformátování Charty 

### ISSUE THREAD

**Issue by Hajneken** [Hajneken/3MA114-Projekt#7]
Dej prosím dohromady všechno co bylo zpracováno k chartě.

**Comment by antydex** [comment]
Peter nemá role a Vláďovi chybí čas a něco o stylu práce.

[Charta.tymu_semifinal.docx](https://github.com/Hajneken/3MA114-Projekt/files/1366335/Charta.tymu_semifinal.docx)

**Comment by antydex** [comment]
Finálka I guess

[Charta.tymu_final.docx](https://github.com/Hajneken/3MA114-Projekt/files/1366345/Charta.tymu_final.docx)

**Comment by Hajneken** [comment]
Good job, uploaduju to na Hlavní stránku
